version: '3.9'

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    # restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    # restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    # restart: always
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    # restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin
      - jaeger
      - prometheus

  service-a:
    container_name: service-a
    build:
      dockerfile: docker/serviceA/Dockerfile
      context: .
    # restart: always
    depends_on:
      - otel-collector
      - zipkin
      - jaeger
      - prometheus    
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/

  service-b:
    container_name: service-b
    build:
      dockerfile: docker/serviceB/Dockerfile
      context: .
    depends_on:
      - otel-collector
      - zipkin
      - jaeger
      - prometheus
    ports:
      - 8081:8081
    volumes:
      - .:/go/src/
